### ISSUE TITLE
Error when trying to use Swift methods

### ISSUE THREAD

**Issue by PseudoC0de** [DrMoriarty/godot_ios_plugin_template#1]
I'm trying to make a plugin that will let users import files from the Files app using `UIDocumentPickerViewController`. For this I'm using a Swift method.

Here is where it fails:
1. Compile the plugin into .xcframework (debug, release_debug, and release) -- `SUCCESS`
2. Add as a plugin to godot and enable -- `SUCCESS`
3. Export godot project to an Xcode project -- `SUCCESS`
4. Build the project within Xcode to export to a physical device -- `ERROR`
```
Undefined symbols for architecture arm64:
  "_OBJC_CLASS_$__TtC12godot_plugin10SwiftClass", referenced from:
      objc-class-ref in import-export-device.release.a(godot_plugin_class.o)
ld: symbol(s) not found for architecture arm64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

My plugin layout is as follows:
`godot_plugin_class.h`
```
#pragma once

#include "core/object.h"

class IosImportExport : public Object {
    GDCLASS(IosImportExport, Object);
    
    static void _bind_methods();
    
public:
    Array importFiles ();
    
    IosImportExport();
    ~IosImportExport();
};
```

`godot_plugin_class.mm`
```
.
.
#import "godot_plugin-Swift.h"
.
.
void IosImportExport::_bind_methods() {
    ClassDB::bind_method(D_METHOD("importFiles"), &IosImportExport::importFiles);
}
.
.
IosImportExport::IosImportExport() {
    NSLog(@"initialize object");
}

IosImportExport::~IosImportExport() {
    NSLog(@"deinitialize object");
}

Array IosImportExport::importFiles() {
    return from_nsarray([SwiftClass importFiles]);
}
```

`SwiftClass.swift`
```
.
.
@objcMembers public class SwiftClass : NSObject
{
    static func importFiles()  -> NSArray {
        print("ENTERING importFiles()")
        let arr : NSArray = ["Hi from swift"]
        
        print("LEAVING importFiles()")
        return arr
}
```
.
.
.
.
I'm pretty new to Godot iOS plugin development, but I've managed to make other plugins work (none of which use any Swift methods), so I'm probably just missing something.

Either way it seems that the `godot_plugin-Swift.h` file isn't actually being used.

By the way, I tried adding the `godot_plugin-Swift.h` file within the `godot_plugin` folder before compiling the plugin, but that didn't do anything.

Any advice?

**Comment by DrMoriarty** [comment]
The standard Godot iOS export template didn't enable swift support. You should add it manually after export. 
See https://github.com/godotengine/godot/pull/46683

**Comment by PseudoC0de** [comment]
> 
> 
> The standard Godot iOS export template didn't enable swift support. You should add it manually after export.
> See [godotengine/godot#46683](https://github.com/godotengine/godot/pull/46683)


Ok, so the steps I took are:

1. Unzip `iphone.zip` in my godot's `templates/3.3.2.stable` folder
2. Edited `godot_ios.xcodeproj/project.pbxproj` to include the following lines:

```
519CD56B24DA849A001E45F0 /* BridgeHeader.swift in Sources */ = {isa = PBXBuildFile; fileRef = 519CD56A24DA849A001E45F0 /* BridgeHeader.swift */; };

519CD56A24DA849A001E45F0 /* BridgeHeader.swift */ = {isa = PBXFileReference; lastKnownFileType = sourcecode.swift; path = BridgeHeader.swift; sourceTree = "<group>"; };

519CD56A24DA849A001E45F0 /* BridgeHeader.swift */,

LastSwiftMigration = 1150;

519CD56B24DA849A001E45F0 /* BridgeHeader.swift in Sources */,

CLANG_ENABLE_MODULES = YES;

SWIFT_OPTIMIZATION_LEVEL = "-Onone";

SWIFT_VERSION = 5.0;

CLANG_ENABLE_MODULES = YES;

SWIFT_OBJC_BRIDGING_HEADER = "godot_ios/godot_ios-Bridging-Header.h";

SWIFT_VERSION = 5.0;
```

3. Added a `BridgeHeader.swift` file in `godot_ios/`, with `import Foundation` inside
4. Re-zip into `iphone.zip` and replace the old one with this new edited template
5. Export for iOS in godot
6. Open in Xcode
7. Product -> Clean Build Folder
8. Click the Build and Run button `ERROR`
```
Undefined symbols for architecture arm64:
  "_OBJC_CLASS_$__TtC12godot_plugin10SwiftClass", referenced from:
      objc-class-ref in import-export-device.release.a(godot_plugin_class.o)
ld: symbol(s) not found for architecture arm64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

Same exact error. I DID notice that this new exported project now has a `BridgeHeader.swift` and `godot_plugin-Swift.h` file though.
![image](https://user-images.githubusercontent.com/16922347/122111046-e39eba00-cde4-11eb-92f2-6ca113c3a41f.png)

Is there something else I'm missing? Maybe a setting within Xcode?

Also if it matters, my `.gdip` file for the plugin looks like this:
```
[config]
name="IosImportExport"
binary="import-export.xcframework"
initialization="godot_ios_import_export_init"
deinitialization="godot_ios_import_export_deinit"

[dependencies]
linked=[]
embedded=[]
system=[]
capabilities=[]
files=["godot_plugin-Swift.h"]
[plist]
```
.
.
.


EDIT:
When I tried running and exporting to my phone in release mode, I got these two errors instead:
```
<unknown>:0: error: error reading '/Users/me/Documents/release_encrypted/godot_ios/godot_ios-Bridging-Header.h'
1 error generated.
```
and
```
<unknown>:0: error: failed to emit precompiled header '/Users/me/Library/Developer/Xcode/DerivedData/My_App-cddfkbhhapxbvaahzpgcyfybbqel/Build/Intermediates.noindex/PrecompiledHeaders/godot_ios-Bridging-Header-swift_H5UW373CWBU8-clang_1XLJ8W28KWL6Y.pch' for bridging header '/Users/me/Documents/release_encrypted/godot_ios/godot_ios-Bridging-Header.h'
```

**Comment by PseudoC0de** [comment]
No luck so far. After getting the last two errors in release mode, I tried creating a `godot_ios/godot_ios-Bridging-Header.h` file. I made it as a copy of godot_plugin-Swift.h (which contains the reference to "SiftClass"):

![image](https://user-images.githubusercontent.com/16922347/122238561-d84f9b00-ce85-11eb-8001-14fe85539ce1.png)

It got rid of the 2 errors, but just gave me the original error back.

`ERROR`
```
Undefined symbols for architecture arm64:
  "_OBJC_CLASS_$__TtC12godot_plugin10SwiftClass", referenced from:
      objc-class-ref in import-export-device.release.a(godot_plugin_class.o)
ld: symbol(s) not found for architecture arm64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

Not sure where I'm going wrong, I think I applied the changes here correctly: godotengine/godot#46683

Is the source of the error still due to how my ios templates are exporting my project, or could something be changed in settings like these?

![image](https://user-images.githubusercontent.com/16922347/122241198-fb7b4a00-ce87-11eb-9c48-e782ab1e2559.png)


Any advice?

**Comment by DrMoriarty** [comment]
Did you added -ObjC to other linker flags?

**Comment by PseudoC0de** [comment]
> 
> 
> Did you added -ObjC to other linker flags?

Yep, tried but no difference was made:

![image](https://user-images.githubusercontent.com/16922347/122243800-046d1b00-ce8a-11eb-9d98-5b391b2d1319.png)
![image](https://user-images.githubusercontent.com/16922347/122243907-177feb00-ce8a-11eb-8f56-9a5564088ccf.png)

**Comment by PseudoC0de** [comment]
Never actually resolved this, but I just got everything working without Swift instead.
